const Data = [
    {id: 0, name: 'Alicia Vela-Bailey', img: 'Alicia-Vela-Bailey', age: '28', location: 'LA, USA', bio: "Recently finished stunt doubling for the movie 'Alita: Battle Angel' and am looking for a new role! Have stunt doubled for major films such as Wonder Woman (Gal Gadot), 'The Punisher' and 'Marvel's Agents of S.H.I.E.L.D'. If you're interested, swipe right and drop me a message!"},
    {id: 1, name: 'Richard Cetrone', img: 'Richard-Cetrone', age: '58', location: 'Pennsylvania, USA', bio: "Just finished working as a stunt performer in the movie Dhaka and am looking for a new role. I've stunt doubled for many characters in both the Marvel and DC universe. Drop me a message if you're interested"},
    {id: 2, name: 'Renae Moneymaker', img: 'Renae-Moneymaker', age: '32', location: 'LA, USA', bio: "From stunt doubling as the champion of the 74th Hunger Games to multiple superheroines from the Marvel Universe, I'm looking for a new action packed role! Let me know if you're interested!" },
    {id: 3, name: 'Bobby Hanton', img: 'Bobby-Hanton', age: '33', location: 'Portsmouth, UK', bio: "Recently finished stunt doubling for Chris Hemsworth(Thor from Avengers) and am currently working as a stunt performer for the new Marvel 'Black Widow' movie. Looking for a new role early next year after I'm finished. Let me know if you're interested! "},
    {id: 4, name: 'Rosie Mac', img: 'Rosie-Mac', age: '22', location: 'Newcastle, UK', bio: "You may know me as Daenerys Stormborn of the House Targaryen, First of Her Name, the Unburnt, Queen of the Andals and the First Men, Khaleesi of the Great Grass Sea, Breaker of Chains, and Mother of Dragons. Recently finished filming and am looking for a new role. Send me a raven if you're interested!"},
    {id: 5, name: 'Tanoai Reed', img: 'Tanoai-Reed', age: '45', location: 'Honolulu, Hawaii', bio: "Stunt Doubled for Dwayne Johnson for 17 years. I can do a range of stunts but mostly specialise in driving and combat. If you're interested, drop me a message!"},
    {id: 6, name: 'Janene Carleton', img: 'Janene-Carleton', age: '36', location: 'Kelowna, Canada', bio: "Just finished working on a film and am looking for a new role. I've 10 years stunt doubling experience, including stunt doubling for Angelina Jolie(Salt), Jessica Biel (Total Recall) as well as for Nick Thurnston (Caesar in Dawn of the Apes). I can do a range of combat stunts but mostly specialise in horse riding. Swipe right if you're intrested!"},
    {id: 7, name: 'Damien-Bryson', img: 'Damien-Bryson', age: '40', location: 'LA, USA', bio: "Tired of looking for booty and am now looking for a new stunt double role. Recently finished working on the TV Series 'Harrow' and am looking for a role which starts around early next year. Drop me a message if you're interested!" },
    {id: 8, name: 'Katie Eischen', img: 'Katie-Eischen', age: '30', location: 'Georgia, USA', bio: "Currently stunt doubling for the movie 'The Long Night'. Looking for a new role starting around early next year. I have a range of experience, stunt doubling in films such as 'Bourne legacy', 'Pretty Little Liars' and recently 'Triple Frontier'. Let me know if you're interested!" },  
];

export default Data;